if ("$ENV{VCPKG_ROOT}" STREQUAL "")
    message(WARNING "You must set VCPKG_ROOT to be the root of your vcpkg installation. \nUsing system libraries instead!\n")
else()
    set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" CACHE STRING "vcpkg toolchain file" FORCE)
    message(STATUS "Using cmake toolchain: ${CMAKE_TOOLCHAIN_FILE}")
endif ()